apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-alpha-apd
  labels:
    app: security-alpha-apd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: security-alpha-apd
  template:
    metadata:
      labels:
        app: security-alpha-apd
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

