apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v2-cds
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      version: v2-cds
  template:
    metadata:
      labels:
        version: v2-cds
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: webpage-server-02
        envFrom:
         - configMapRef:
                name: {{ .Values.configMap.name }}
